networks:
  homeserver:
    name: "home-server"
    ipam:
      driver: default
      config:
        # internal IP
        #CIDR address: first 24 bit are blocked, last 8 bit are free (0-255)
        - subnet: ${BASE_INTERNAL_IP}/24

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      #:ro, read only access
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
      - ./volumes/traefik/config/traefik.yml:/traefik.yml:ro
      - ./volumes/traefik/config/config.yml:/config.yml
      #- ./volumes/traefik/config/usersfile:/usersfile:ro
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${TRAEFIK_INTERNAL_IP}
    environment:
      # Used in traefik config.yml file [./volumes/traefik/config/config.yml]!
      - DOMAIN_NAME
      - WHOAMI_INTERNAL_IP
      - WHOAMI_PORT
      - FILEBROWSER_INTERNAL_IP
      - FILEBROWSER_PORT
      - TELEGRAM_BOT_INTERNAL_IP
      - TELEGRAM_BOT_PORT
      - HOMEPAGE_INTERNAL_IP
      - HOMEPAGE_PORT
      - EMBY_INTERNAL_IP
      - EMBY_PORT
      - SONARR_INTERNAL_IP
      - SONARR_PORT
      - QBITTORRENT_INTERNAL_IP
      - QBITTORRENT_PORT
      - JACKETT_INTERNAL_IP
      - JACKETT_PORT
      - IMMICH_SERVER_INTERNAL_IP
      - IMMICH_SERVER_PORT
      #- PORTAINER_INTERNAL_IP
      #- PORTAINER_FE_PORT
      #- PORTAINER_EDGE_PORT
      # Set values using env vars
      - TRAEFIK_CERTIFICATESRESOLVERS_MAIN_ACME_EMAIL=${USER_MAIL}
      - NAMECOM_USERNAME=${NAMECOM_USERNAME_PROD}
      - NAMECOM_API_TOKEN=${NAMECOM_API_TOKEN_PROD}
      - NAMECOM_SERVER=${NAMECOM_SERVER_PROD}
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "whoami-sensor-service"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${WHOAMI_INTERNAL_IP}
    restart: unless-stopped

  filebrowser:
    image: "hurlenko/filebrowser"
    container_name: "filebrowser"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${FILEBROWSER_INTERNAL_IP}
    #user id: group id of the user inside the docker container
    user: "root:root"
    volumes:
      # mapping entire /mnt folder, if you want to mount a specific drive you can change this path.
      - /mnt/ext-disk-01/data:/data
      # mapping volumes folder inside /home/home-server/docker-server
      - ./volumes/filebrowser/config:/config
      - ./volumes/filebrowser/branding:/branding
      - ./volumes/filebrowser/config/filebrowser.db:/.filebrowser.db
      - ./volumes/filebrowser/config/filebrowser.json:/.filebrowser.json
    environment:
      - FB_BASEURL=/volumes/filebrowser
    restart: unless-stopped

  telegram-bot:
    build: ./volumes/telegram-bot/
    container_name: "telegram-bot"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${TELEGRAM_BOT_INTERNAL_IP}
    volumes:
      - /opt/vc:/opt/vc:ro
    devices:
      - "/dev/vchiq:/dev/vchiq"
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LD_LIBRARY_PATH=/usr/lib
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: "homepage"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${HOMEPAGE_INTERNAL_IP}
    volumes:
      - ./volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /mnt/ext-disk-01/data:/data:ro
    environment:
      - TZ=${TZ}
      - HOMEPAGE_VAR_DOMAIN_NAME=${DOMAIN_NAME}
      - HOMEPAGE_VAR_TELEGRAM_BOT=${TELEGRAM_BOT_URL}
      - HOMEPAGE_VAR_GITHUB=${GITHUB_URL}
      - HOMEPAGE_VAR_REDDIT=${REDDIT_URL}
      - HOMEPAGE_VAR_SONARR_APIKEY=${SONARR_APIKEY}
      - HOMEPAGE_VAR_JACKETT=${BASE_LOCALHOST}
      - HOMEPAGE_VAR_QBITTORRENT=${BASE_LOCALHOST}
      - HOMEPAGE_VAR_IMMICH_APIKEY=${IMMICH_APIKEY}
    restart: unless-stopped

  ### IMMICH SERVICES ###
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ 'start.sh', 'immich' ]
    user: "root:root"
    cpus: 3
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH_SHARED}:/usr/src/app/external/shared
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      homeserver:
        # internal IP
        ipv4_address:
          ${IMMICH_SERVER_INTERNAL_IP}
    ports:
      - 2283:${IMMICH_SERVER_PORT}
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ 'start.sh', 'microservices' ]
    user: "root:root"
    cpus: 3
    networks:
      homeserver:
        # internal IP
        ipv4_address:
          ${IMMICH_MS_INTERNAL_IP}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH_SHARED}:/usr/src/app/external/shared
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  # However, disabling all jobs will not disable the machine learning service itself.
  # To prevent it from starting up at all in this case, you can comment out the immich-machine-learning section of the docker-compose.yml.
  #immich-machine-learning:
  #  container_name: immich_machine_learning
  #  # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
  #  # Example tag: ${IMMICH_VERSION:-release}-cuda
  #  image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #  # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #  #   file: hwaccel.ml.yml
  #  #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #  volumes:
  #    - model-cache:/cache
  #  env_file:
  #    - .env
  #  restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    user: "root:root"
    networks:
      homeserver:
        # internal IP
        ipv4_address:
          ${REDIS_INTERNAL_IP}
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    user: "root:root"
    networks:
      homeserver:
        # internal IP
        ipv4_address:
          ${POSTGRES_INTERNAL_IP}
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ### DISABLED STREAMING CONTAINERS ###
  emby:
    image: emby/embyserver_arm64v8
    container_name: emby
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${EMBY_INTERNAL_IP}
    ports:
      - ${EMBY_PORT}:${EMBY_PORT} # HTTP port
      - '8920:8920' # HTTPS port
      - '7359:7359'
      - '1900:1900'
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1000 # The GID to run emby as (default 2)
      - GIDLIST=0 # A comma-separated list of additional GIDs to run emby as (default: 2)
      - TZ=${TZ}
    volumes:
      - ./volumes/emby/config:/config
      - ./volumes/sonarr/data/torrents:/media
    devices:
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: unless-stopped
    profiles: [ 'streaming' ]

  sonarr:
    image: ghcr.io/hotio/sonarr:release
    container_name: sonarr
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${SONARR_INTERNAL_IP}
    #ports:
    #  - 8989:8989
    volumes:
      - ./volumes/sonarr/config:/config
      - ./volumes/sonarr/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
    profiles: [ 'streaming' ]

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${QBITTORRENT_INTERNAL_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT}
      - TORRENTING_PORT=6881
    volumes:
      - ./volumes/qbittorrent/config:/config
      - ./volumes/sonarr/data/torrents:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    profiles: [ 'streaming' ]

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${JACKETT_INTERNAL_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./volumes/jackett/config:/config
      - ./volumes/sonarr/data/torrents:/downloads
    ports:
      - ${JACKETT_PORT}:${JACKETT_PORT}
    restart: unless-stopped
    profiles: [ 'streaming' ]


