
networks:
  homeserver:
    name: "home-server"
    ipam:
      driver: default
      config:
        # internal IP
        #CIDR address: first 24 bit are blocked, last 8 bit are free (0-255)
        - subnet: ${BASE_INTERNAL_IP}/24
          
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      #:ro, read only access
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
      - ./volumes/traefik/config/traefik.yml:/traefik.yml:ro
      - ./volumes/traefik/config/config.yml:/config.yml
      #- ./volumes/traefik/config/usersfile:/usersfile:ro
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${TRAEFIK_INTERNAL_IP}
    environment:
      # Used in traefik config.yml file [./volumes/traefik/config/config.yml]!
      - DOMAIN_NAME
      - WHOAMI_INTERNAL_IP
      - WHOAMI_PORT
      - FILEBROWSER_INTERNAL_IP
      - FILEBROWSER_PORT
      - TELEGRAM_BOT_INTERNAL_IP
      - TELEGRAM_BOT_PORT
      - HOMEPAGE_INTERNAL_IP
      - HOMEPAGE_PORT
      - EMBY_INTERNAL_IP
      - EMBY_PORT
      #- PORTAINER_INTERNAL_IP
      #- PORTAINER_FE_PORT
      #- PORTAINER_EDGE_PORT
      # Set values using env vars
      - TRAEFIK_CERTIFICATESRESOLVERS_MAIN_ACME_EMAIL=${USER_MAIL}
      - NAMECOM_USERNAME=${NAMECOM_USERNAME_PROD}
      - NAMECOM_API_TOKEN=${NAMECOM_API_TOKEN_PROD}
      - NAMECOM_SERVER=${NAMECOM_SERVER_PROD}
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: " "
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${WHOAMI_INTERNAL_IP}
    restart: unless-stopped

  filebrowser:
    image: "hurlenko/filebrowser"
    container_name: "filebrowser"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${FILEBROWSER_INTERNAL_IP}
    #user id: group id of the user inside the docker container
    user: "root:root"
    volumes:
      # mapping entire /mnt folder, if you want to mount a specific drive you can change this path.
      - /mnt/ext-disk-01/data:/data
      # mapping volumes folder inside /home/home-server/docker-server
      - ./volumes/filebrowser/config:/config
      - ./volumes/filebrowser/branding:/branding
      - ./volumes/filebrowser/config/filebrowser.db:/.filebrowser.db
      - ./volumes/filebrowser/config/filebrowser.json:/.filebrowser.json
    environment:
      - FB_BASEURL=/volumes/filebrowser
    restart: unless-stopped

  telegram-bot:
    build: ./volumes/telegram-bot/
    container_name: "telegram-bot"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${TELEGRAM_BOT_INTERNAL_IP}
    volumes:
      - /opt/vc:/opt/vc:ro
    devices:
      - "/dev/vchiq:/dev/vchiq"
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LD_LIBRARY_PATH=/usr/lib
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: "homepage"
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${HOMEPAGE_INTERNAL_IP}
    volumes:
      - ./volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /mnt/ext-disk-01/data:/data:ro
    environment:
      - TZ=${TZ}
      - HOMEPAGE_VAR_DOMAIN_NAME=${DOMAIN_NAME}
      - HOMEPAGE_VAR_TELEGRAM_BOT=${TELEGRAM_BOT_URL}
      - HOMEPAGE_VAR_GITHUB=${GITHUB_URL}
      - HOMEPAGE_VAR_REDDIT=${REDDIT_URL}
    restart: unless-stopped

  emby:
    image: emby/embyserver_arm64v8
    container_name: emby
    networks:
      homeserver:
        # internal IP
        ipv4_address: ${EMBY_INTERNAL_IP}
    ports:
      - '8096:8096' # HTTP port
      - '8920:8920' # HTTPS port
      - '7359:7359'
      - '1900:1900'
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1000 # The GID to run emby as (default 2)
      - GIDLIST=0 # A comma-separated list of additional GIDs to run emby as (default: 2)
      - TZ=${TZ}
    volumes:
      - ./volumes/emby/config:/config
      - ./volumes/emby/media-test:/media
    devices:
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: unless-stopped
