---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: My Awesome Homepage
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
headerStyle: clean
showStats: true